
plugins {
    id 'architectury-plugin'
    id 'dev.architectury.loom'
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    loader('quilt')
}

loom {
    silentMojangMappingsLicense()
    accessWidenerPath = project(':lunararc-common').file('src/main/resources/lunararc.accesswidener')
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentQuilt.extendsFrom common
}

dependencies {
    minecraft libs.minecraft
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${libs.versions.minecraft.get()}:${libs.versions.parchment.get()}@zip")
    }
    modImplementation libs.quilt.loader
    modImplementation "net.fabricmc:fabric-loader:${libs.versions.fabric.loader.get()}"
    modImplementation libs.fabric.api
    modImplementation(libs.fabric.permissions.api) { transitive = false }
    include(libs.fabric.permissions.api) { transitive = false }
    common(project(path: ':lunararc-common', configuration: 'namedElements')) { transitive false }
    shadowCommon(project(path: ':lunararc-common', configuration: 'transformProductionQuilt')) { transitive false }
    implementation libs.lunararc.api
    implementation libs.paper.api
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'project_name', rootProject.name
    inputs.property 'minecraft', libs.versions.minecraft.get()
    inputs.property 'quilt_loader', libs.versions.quilt.loader.get()
    filesMatching('quilt.mod.json') {
        expand version: project.version, project_name: rootProject.name,
               minecraft: libs.versions.minecraft.get(), quilt_loader: libs.versions.quilt.loader.get()
    }
}

shadowJar {
    configurations = [project.configurations.shadowCommon]
    archiveClassifier.set('dev-shadow')
    exclude 'fabric.mod.json'
    exclude 'META-INF/mods.toml'
    exclude 'META-INF/neoforge.mods.toml'
}

remapJar {
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
}
