plugins {
    id 'architectury-plugin'
    id 'dev.architectury.loom'
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    silentMojangMappingsLicense()
    accessWidenerPath = project(':lunararc-common').file('src/main/resources/lunararc.accesswidener')
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    minecraft libs.minecraft
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${libs.versions.minecraft.get()}:${libs.versions.parchment.get()}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${libs.versions.fabric.loader.get()}"
    modImplementation libs.fabric.api
    modImplementation(libs.fabric.permissions.api) { transitive = false }
    include(libs.fabric.permissions.api) { transitive = false }
    common(project(path: ':lunararc-common', configuration: 'namedElements')) { transitive = false }
    shadowBundle(project(path: ':lunararc-common', configuration: 'transformProductionFabric')) { transitive = false }
    implementation libs.lunararc.api
    shadowBundle libs.lunararc.api
    implementation libs.paper.api
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'project_name', rootProject.name
    inputs.property 'minecraft', libs.versions.minecraft.get()
    inputs.property 'fabric_loader', libs.versions.fabric.loader.get()
    inputs.property 'java_runtime', libs.versions.java.runtime.get()
    filesMatching('fabric.mod.json') {
        expand version: project.version, project_name: rootProject.name,
               minecraft: libs.versions.minecraft.get(), fabric_loader: libs.versions.fabric.loader.get(),
               java_runtime: libs.versions.java.runtime.get()
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier.set('dev-shadow')
    exclude 'quilt.mod.json'
    exclude 'META-INF/mods.toml'
    exclude 'META-INF/neoforge.mods.toml'
}

remapJar {
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
}
