
plugins {
    id 'java-library'
}

sourceSets {
    entry {
        java.srcDir 'src/entry/java'
    }
}

tasks.named('compileEntryJava') {
    options.release = 8
}

dependencies {
    implementation libs.lunararc.api
    implementation project(':i18n-config')
    implementation libs.gson
    implementation libs.jetbrains.annotations
}

processResources {

    inputs.property 'version',       project.version
    inputs.property 'project_name',  rootProject.name
    inputs.property 'minecraft',     libs.versions.minecraft.get()
    inputs.property 'java_runtime',   libs.versions.java.runtime.get()
    inputs.property 'paper_api',     libs.versions.paper.api.get()
    inputs.property 'neoforge',      libs.versions.neoforge.get()
    inputs.property 'forge',         libs.versions.forge.get()
    inputs.property 'fabric_loader', libs.versions.fabric.loader.get()
    inputs.property 'fabric_installer', libs.versions.fabric.installer.get()
    inputs.property 'quilt_loader',  libs.versions.quilt.loader.get()
    inputs.property 'quilt_installer', libs.versions.quilt.installer.get()
    inputs.property 'paper_build',   libs.versions.paper.build.get()
    inputs.property 'data_version',  libs.versions.data.version.get()
    inputs.property 'build_name',    libs.versions.build.name.get()

    filesMatching('lunararc-launcher.properties') {
        expand(
            version:       project.version,
            project_name:  rootProject.name,
            minecraft:     libs.versions.minecraft.get(),
            javaRuntime:   libs.versions.java.runtime.get(),
            paperApi:      libs.versions.paper.api.get(),
            neoforge:      libs.versions.neoforge.get(),
            forge:         libs.versions.forge.get(),
            fabric:        libs.versions.fabric.loader.get(),
            fabricInstaller: libs.versions.fabric.installer.get(),
            quilt:         libs.versions.quilt.loader.get(),
            quiltInstaller: libs.versions.quilt.installer.get(),
            paperBuild:    libs.versions.paper.build.get(),
            dataVersion:   libs.versions.data.version.get(),
            buildName:     libs.versions.build.name.get()
        )
    }
}
